### ISSUE TITLE
Serve on port 80

### ISSUE THREAD

**Issue by pierrickrouxel** [grimneko/iocage-plugin-homebridge#1]
Hello,

I tried your homebridge plugin. Thank you it's a really convenient way to install homebridge on freenas.
By default homebrige-ui is bound to port 8080 but each jail has its proper network address. Serving UI on port 80 provides a simple way to access it (with DNS for example).

It is possible to change default port to 80 ?

Thank you.

**Comment by grimneko** [comment]
Certainly, you want to edit the "port: 8080" setting within the platforms section in the /root/.homebridge/config.json (within the jail), it should work fine if you change it to 80 instead of 8080. Just need a restart to work.

More information about the Homebridge Config UI X that supplying the ui for this package can be found here: https://www.npmjs.com/package/homebridge-config-ui-x

**Comment by pierrickrouxel** [comment]
Yes I know how to do but I think it would be better to change it by default in plugin, you don't know ?

**Comment by pierrickrouxel** [comment]
7b0b271
Thank you !

**Comment by pierrickrouxel** [comment]
You missed ui.json.

**Comment by pierrickrouxel** [comment]
c4e5e5c
Thank you.
